#cloud-config
timezone: EST

package_update: true
package_upgrade: true
package_reboot_if_required: true

packages:
  - git

runcmd:
  - git clone https://github.com/dtag-dev-sec/tpotce /root/tpot
  - cp /root/tpot/iso/installer/tpot.conf.dist  /root/tpot.conf
  - /root/tpot/iso/installer/install.sh --type=auto --conf=/root/tpot.conf
  - /sbin/shutdown -r +5

write_files:
  - encoding: b64
    owner: root:root
    path: /root/tpot.conf
    permissions: '0600'
  - path: /etc/sysctl.d/60-enable-ipv6.conf
    owner: root
    content: |
    net.ipv6.conf.all.disable_ipv6=0
    net.ipv6.conf.default.disable_ipv6=0
    net.ipv6.conf.lo.disable_ipv6=0